class_name Cost
extends Reference


const FRIENDLY_SMALL_UPGRADE := 400
const FRIENDLY_MEDIUM_UPGRADE := 1600

const FRIENDLY_RALLY := 0
const FRIENDLY_MOVE := 0
const FRIENDLY_STOP := 0
const FRIENDLY_INFO := 0

const BUILDING_EMPTY := 0
const BUILDING_BASE := 0
const BUILDING_TOWER := 200
const BUILDING_FARM := 1000

const BUILDING_BASE_SMALL_UPGRADE := 1000
const BUILDING_BASE_MEDIUM_UPGRADE := 10000
const BUILDING_TOWER_SMALL_UPGRADE := 1000
const BUILDING_TOWER_MEDIUM_UPGRADE := 4000
const BUILDING_FARM_SMALL_UPGRADE := 2000
const BUILDING_FARM_MEDIUM_UPGRADE := 8000

const BUILDING_OCCUPY := 0
const BUILDING_VACATE := 0
const BUILDING_RECYCLE := 0
const BUILDING_STOP := 0
const BUILDING_INFO := 0

const HERO := 0

const SMALL_WORKER := 0
const MEDIUM_WORKER := FRIENDLY_SMALL_UPGRADE
const LARGE_WORKER := FRIENDLY_MEDIUM_UPGRADE

const SMALL_BASE := 0
const MEDIUM_BASE := BUILDING_BASE_SMALL_UPGRADE
const LARGE_BASE := BUILDING_BASE_MEDIUM_UPGRADE

const SMALL_TOWER := BUILDING_TOWER
const MEDIUM_TOWER := BUILDING_TOWER_SMALL_UPGRADE
const LARGE_TOWER := BUILDING_TOWER_MEDIUM_UPGRADE

const SMALL_FARM := 0
const MEDIUM_FARM := 0
const LARGE_FARM := 0

const BUILDING_ENEMY_SPAWN := 0
const ENEMY_SMALL := 0
const ENEMY_LARGE := 0
